# Generated by Django 2.1.7 on 2019-04-26 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('estado', models.BooleanField(blank=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('minicodigo', models.CharField(blank=True, max_length=45, null=True, verbose_name='Mini Código')),
                ('codigo_barra', models.CharField(blank=True, max_length=45, null=True, verbose_name='Código de Barra')),
                ('cantidad', models.FloatField(blank=True, default=0, null=True, verbose_name='Cantidad')),
                ('imagen', models.ImageField(blank=True, default='producto-default.png', null=True, upload_to='', verbose_name='Imagen')),
                ('estado', models.BooleanField(blank=True, default=True, verbose_name='Estado')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Categoria', verbose_name='Categoría')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
