# Generated by Django 2.1.7 on 2019-05-06 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pedidoproductos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('modificacion', models.DateTimeField(auto_now=True)),
                ('cantidad', models.FloatField(blank=True, default=0, null=True)),
                ('activo', models.BooleanField(blank=True, default=True)),
                ('estado', models.BooleanField(blank=True, default=True)),
            ],
            options={
                'db_table': 'app_pedido_productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('documento', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=45)),
                ('estado', models.BooleanField(blank=True, default=True, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechainicio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Inicio')),
                ('fechafin', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de caducidad')),
                ('tipopedido', models.IntegerField(blank=True, default=1)),
                ('estado', models.BooleanField(blank=True, default=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Cliente')),
                ('productos', models.ManyToManyField(to='app.Producto')),
            ],
            options={
                'ordering': ['-fechainicio'],
            },
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nombre']},
        ),
    ]
