# Generated by Django 2.1.7 on 2019-08-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190506_1402'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nombre']},
        ),
        migrations.AddField(
            model_name='producto',
            name='tipoproducto',
            field=models.IntegerField(default=1, verbose_name='Tipo Producto'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='documento',
            field=models.CharField(max_length=8),
        ),
    ]
